### ISSUE TITLE
Need to host storybook

### ISSUE THREAD

**Issue by subeshb1** [subeshb1/infinity-react-cards#3]

**Comment by HurricaneInteractive** [comment]
Happy to look into this.

**Findings**
Not going to open a PR because you'll have to do a bit of configuring on your side. I recommend setting the project up to use [Netlify](https://www.netlify.com). You'll then be able to link this repo and build storybook to deploy it as a static site.

Once you have it set up. Look at [this guide](https://www.netlify.com/blog/2019/01/29/sharing-the-love-with-netlify-deployment-badges/#how-to-add-a-deployment-badge) to add a Netlify badge to your README.
